=== frankkulak/mods-web-data/schemas/mod.schema.json
{
  "$schema": "http://json-schema.org/schema",
  "definitions": {
    "downloadList": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "host",
          "href"
        ],
        "properties": {
          "host": {
            "description": "Name of website where download is hosted.",
            "type": "string"
          },
          "href": {
            "description": "HREF to use in download link.",
            "type": "string"
          }
        }
      }
    },
    "expansionPacks": {
      "type": "string",
      "enum": [
        "Get to Work",
        "Get Together",
        "City Living",
        "Cats & Dogs",
        "Seasons",
        "Get Famous",
        "Island Living",
        "Discover University",
        "Eco Lifestyle",
        "Snowy Escape",
        "Cottage Living",
        "High School Years",
        "Growing Together",
        "For Rent",
        "Life & Death",
        "Businesses & Hobbies",
        "Enchanted by Nature",
        "Adventure Awaits",
        "Royalty & Legacy"
      ]
    },
    "gamePacks": {
      "type": "string",
      "enum": [
        "Outdoor Retreat",
        "Spa Day",
        "Dine Out",
        "Vampires",
        "Parenthood",
        "Jungle Adventure",
        "Strangerville",
        "Realm of Magic",
        "Journey to Batuu",
        "Dream Home Decorator",
        "My Wedding Stories",
        "Werewolves"
      ]
    },
    "stuffPacks": {
      "type": "string",
      "enum": [
        "Luxury Party Stuff",
        "Perfect Patio Stuff",
        "Cool Kitchen Stuff",
        "Spooky Stuff",
        "Movie Hangout Stuff",
        "Romantic Garden Stuff",
        "Kids Room Stuff",
        "Backyard Stuff",
        "Vintage Glamour Stuff",
        "Bowling Night Stuff",
        "Fitness Stuff",
        "Toddler Stuff",
        "Laundry Day Stuff",
        "My First Pet Stuff",
        "Moschino Stuff",
        "Tiny Living Stuff",
        "Nifty Knitting Stuff",
        "Paranormal Stuff"
      ]
    },
    "kitPacks": {
      "type": "string",
      "enum": [
        "Throwback Fit Kit",
        "Country Kitchen Kit",
        "Bust the Dust Kit",
        "Courtyard Oasis Kit",
        "Fashion Street Kit",
        "Industrial Loft Stuff",
        "Incheon Arrivals Kit",
        "Modern Menswear Kit",
        "Blooming Rooms Kit",
        "Carnaval Streetwear Kit",
        "Decor to the Max Kit",
        "Moonlight Chic Kit",
        "Little Campers Kit",
        "First Fits Kit",
        "Desert Luxe Kit",
        "Pastel Pop Kit",
        "Everyday Clutter Kit",
        "Simtimates Collection Kit",
        "Bathroom Clutter Kit",
        "Greenhouse Haven Kit",
        "Basement Treasures Kit"
      ]
    },
    "packs": {
      "type": "object",
      "properties": {
        "eps": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/expansionPacks"
          }
        },
        "gps": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/gamePacks"
          }
        },
        "sps": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/stuffPacks"
          }
        },
        "kits": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/kitPacks"
          }
        }
      }
    }
  },
  "type": "object",
  "required": [
    "description",
    "name",
    "pages",
    "stage",
    "status",
    "tagline"
  ],
  "properties": {
    "skipIndex": {
      "description": "If true, then don't list this mod in the index.",
      "type": "boolean"
    },
    "description": {
      "description": "Brief description of this mod.",
      "type": "string"
    },
    "documentation": {
      "description": "List of places to download the documentation.",
      "$ref": "#/definitions/downloadList"
    },
    "downloads": {
      "description": "List of places to download the mod.",
      "$ref": "#/definitions/downloadList"
    },
    "downloadWarning": {
      "description": "HTML content to display while downloading the mod.",
      "type": "string"
    },
    "earlyAccess": {
      "description": "What kind of early access this mod is in, if any.",
      "type": "string",
      "enum": [
        "alpha",
        "beta",
        "none"
      ]
    },
    "featured": {
      "description": "Whether or not this mod should be displayed more prominently.",
      "type": "boolean"
    },
    "hasNoCustomStrings": {
      "description": "Whether or not this mod has no custom strings (intentionally negated so default can be false).",
      "type": "boolean"
    },
    "hideTranslations": {
      "description": "Whether or not to hide the translations section.",
      "type": "boolean"
    },
    "lastUpdated": {
      "description": "The date of the last update to this mod.",
      "type": "string"
    },
    "name": {
      "description": "Display name of this mod.",
      "type": "string"
    },
    "notTranslatable": {
      "description": "Whether or not this mod cannot be translated (intentionally negated so default can be false).",
      "type": "boolean"
    },
    "pages": {
      "description": "List of pages to display for this mod.",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "title",
          "html"
        ],
        "properties": {
          "title": {
            "description": "Label to display on the tab for this page.",
            "type": "string"
          },
          "html": {
            "description": "Name of HTML file to use for this page's content.",
            "type": "string"
          }
        }
      }
    },
    "publicRelease": {
      "description": "The date this mod goes public.",
      "type": "string"
    },
    "recommendedPacks": {
      "description": "Packs that enhance this mod's gameplay.",
      "$ref": "#/definitions/packs"
    },
    "requiredPacks": {
      "description": "Packs that are required for this mod to work. If empty, it is BG compatible.",
      "$ref": "#/definitions/packs"
    },
    "seoTags": {
      "description": "Tags to use for SEO with this mod.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "stage": {
      "description": "Current development stage of this mod.",
      "type": "string",
      "enum": [
        "alpha",
        "beta",
        "public",
        "wip"
      ]
    },
    "status": {
      "description": "The current status of this mod.",
      "type": "string",
      "enum": [
        "broken",
        "unreleased",
        "untested",
        "working"
      ]
    },
    "tagline": {
      "description": "Very brief text to display under mod name.",
      "type": "string"
    },
    "translations": {
      "description": "List of available translations.",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "code",
          "translators"
        ],
        "properties": {
          "code": {
            "description": "The code for this locale.",
            "type": "string",
            "enum": [
              "ENG_US",
              "CHS_CN",
              "CHT_CN",
              "CZE_CZ",
              "DAN_DK",
              "DUT_NL",
              "FIN_FI",
              "FRE_FR",
              "GER_DE",
              "ITA_IT",
              "JPN_JP",
              "KOR_KR",
              "NOR_NO",
              "POL_PL",
              "POR_BR",
              "RUS_RU",
              "SPA_EA",
              "SWE_SE"
            ]
          },
          "href": {
            "description": "Link to mod, if it's not included in download.",
            "type": "string"
          },
          "translators": {
            "description": "List of people who contributed to this translation.",
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "name"
              ],
              "properties": {
                "name": {
                  "description": "Name of translator.",
                  "type": "string"
                },
                "href": {
                  "description": "Optional link to this translator's web page.",
                  "type": "string"
                }
              }
            }
          },
          "outdated": {
            "description": "Whether or not this translation is outdated.",
            "type": "boolean"
          }
        }
      }
    },
    "version": {
      "description": "Current version of the mod.",
      "type": "string"
    },
    "videos": {
      "description": "List of videos showcasing the mod.",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "creator",
          "name",
          "platform",
          "href"
        ],
        "properties": {
          "creator": {
            "description": "Who made the video.",
            "type": "string"
          },
          "href": {
            "description": "Link where the video can be found.",
            "type": "string"
          },
          "name": {
            "description": "Name of the video.",
            "type": "string"
          },
          "platform": {
            "description": "Where the video is posted.",
            "type": "string"
          }
        }
      }
    }
  }
}

=== frankkulak/mods-web-data/build/mods/buy-bits-and-pieces.json
{"name":"Buy Bits and Pieces","tagline":"Trade simoleons for bits/pieces","description":"Gathering bits and pieces by recycling materials can get repetitive and annoying. This mod allows you to buy them with simoleons instead, for those of you that don't like to use cheats.","version":"1.0.5","lastUpdated":"October 21, 2020","stage":"public","status":"untested","requiredPacks":{"eps":["Eco Lifestyle"]},"pages":[{"title":"Details","html":"<h2>Features</h2><ul><li>Buy bits and pieces with simoleans (10 for ยง100)</li><p class=\"footnote\">Click on any trash can (including most CC) and select the \"Buy Bits\" or \"Buy Pieces\" interactions</p><li>Fill up the power generator with simoleans</li><p class=\"footnote\">Click on the generator and select \"Add Fuel\" to fill it up for ยง250 (no bits, pieces, or bio-fuel required)</p></ul>"},{"title":"Changelog","html":"<h2>1.0.5 (October 21, 2020)</h2><ul><li>Add Chinese translation (by MuMu).</li></ul><h2>1.0.4 (September 15, 2020)</h2><ul><li><em>Actually</em> fix file structure issue that may cause some errors on Windows installation.</li><p class=\"footnote\">Sorry about that!</p></ul><h2>1.0.3 (September 13, 2020)</h2><ul><li>Add French translation (by Rebecca).</li></ul><h2>1.0.2 (September 12, 2020)</h2><ul><li>Fix animation issue that caused sims to pour fuel where they are standing rather than at the generator.</li></ul><h2>1.0.1 (September 12, 2020)</h2><ul><li>Fix file structure issue that may cause some errors on Windows installation.</li><p class=\"footnote\">EDIT: This fix did not work - see v1.0.4.</p><li>Provide Italian translation (by me).</li></ul><h2>1.0 (September 9, 2020)</h2><ul><li>Add the buy bits/pieces interactions to all trash cans.</li><li>Add an interaction to fill the generator with ยง250.</li></ul>"}],"translations":[{"code":"ENG_US","translators":[{"name":"Frankk"}]},{"code":"FRE_FR","translators":[{"name":"Kimikosoma","href":"https://modsims4.fr/"}]},{"code":"ITA_IT","translators":[{"name":"Frankk"}]},{"code":"CHT_CN","outdated":true,"translators":[{"name":"MuMu"}]}],"downloads":[{"host":"Sim File Share","href":"http://www.simfileshare.net/download/2017359/"},{"host":"Google Drive","href":"https://drive.google.com/drive/folders/1igN6N0DPyIw8QwT-ZdOwp6TeQTovlqRz?usp=sharing"}]}

=== frankkulak/mods-web-data/build/mods/followers-for-fame.json
{"name":"Followers for Fame","tagline":"Sync followers with fame level","description":"Can you really call yourself a 'Global Superstar' when you only have 12 followers on Simstagram? This mod automatically gives your sim followers whenever they gain fame.","version":"1.1.3","lastUpdated":"May 25, 2022","stage":"public","status":"working","seoTags":["famous","celebrity","auto"],"requiredPacks":{"eps":["Get Famous"]},"pages":[{"title":"Details","html":"<h2>Summary</h2><div class=\"paragraphs\"><p>This mod keeps your sims' follower counts in sync with their fame level. It adds followers when they gain fame, and removes followers when they lose fame. It also provides some cheats to add/remove/set followers.</p><p class=\"danger\"><strong class=\"danger\">Be advised</strong>: This mod does not account for Social Bunny from High School Years; it only syncs followers for regular social media.</p></div><hr><h2>Automatic followers</h2><ul><li>Gain followers when you gain fame.</li><p class=\"footnote\">Interactions that add followers: Selling a painting or photo, making an app or game, licensing a song or lyrics, publishing a book, being nominated for an award, accepting an award, completing a work day as an actor, ranking up as a celebrity, and getting positive PR through the PR agency.</p><li>Lose followers when you lose fame.</li><p class=\"footnote\">Interactions that remove followers: Ranking down as a celebrity and getting bad PR through the PR agency.</p></ul><br><p>Exact amounts for gains/losses are random, but are influenced by the sim's interaction, current fame rank, and current follower count.</p><p class=\"footnote\">Example: A non-famous sim with 10 followers will gain very few for a painting, but a famous sim with 10 million followers will gain hundreds of thousands for a movie.</p><h2>Initial followers for famous sims</h2><p>When you first load a save with this mod installed, all of your famous sims will have their follower counts checked. If they do not have any followers, then they will be given a random amount that corresponds with their fame level.</p><p class=\"footnote\">1 star = ~1k, 2 stars = ~10k, 3 stars = ~100k, 4 stars = ~1M, 5 stars = ~10M</p><h2>Customization & cheats</h2><p>For all of the following, you will need to enable testing cheats with the <code>testingcheats on</code> command.</p><br><h4>Disabling automatic followers for a sim</h4><p>All sims have auto followers on by default, but you can turn it off for specific sims by shift-clicking them and selecting the \"Follower Cheats\" menu option.</p><br><h4>Manually add/remove followers</h4><div class=\"paragraphs\"><p>You can add/remove followers with interactions by shift-clicking a sim and going to the \"Follower Cheats\" menu option.</p><p>Alternatively, you can also use the following console cheats. They each accept 3 arguments, the first being the number of followers, the second being the sim's first name, and the third being their last name.</p><ul><li><code>fkff.add_followers</code> &rarr; Add the specified number of followers to the named sim.</li><p class=\"footnote\">Example: <code>fkff.add_followers 500 bella goth</code> &rarr; Add 500 followers to Bella Goth</p><li><code>fkff.remove_followers</code> &rarr; Remove the specified number of followers from the named sim.</li><p class=\"footnote\">Example: <code>fkff.remove_followers 1000 eliza pancakes</code> &rarr; Remove 1,000 followers from Eliza Pancakes</p><li><code>fkff.set_followers</code> &rarr; Set the named sim's followers to the specified amount.</li><p class=\"footnote\">Example: <code>fkff.set_followers 50000000 judith ward</code> &rarr; Set Judith Ward's follower count to 50 million.</p></ul></div>"},{"title":"Changelog","html":"<h2>1.1.3 (May 25, 2022)</h2><ul><li>Update English strings for pronoun patch.</li></ul><h2>1.1.2 (March 11, 2022)</h2><ul><li>Add Italian and Russian translations.</li></ul><h2>1.1.1 (July 25, 2021)</h2><ul><li>Add Spanish, Chinese, Portuguese, and Norwegian translations.</li></ul><h2>1.1 (November 24, 2020)</h2><ul><li>Make follower gains/losses more realistic (consider current follower count when determining number of followers to add/remove, and lower follower gains for non-famous sims substantially).</li><li>Console cheats to add, remove, or set a specific number of followers for any sim.</li><li>Setting to disable automatic followers for particular sims.</li><li>Automatically give all existing famous sims a starting amount of followers.</li><li>Add Polish translation (by Osqar).</li></ul><h2>1.0.2 (September 15, 2020)</h2><ul><li>Actually fix file structure issue that may cause some errors on Windows installation. Sorry about that!</li></ul><h2>1.0.1 (September 12, 2020)</h2><ul><li>Fix file structure issue that may cause some errors on Windows installation. EDIT: This fix did not work - see v1.0.2.</li></ul><h2>1.0 (July 26, 2020)</h2><ul><li>End 1.0 beta phase.</li></ul><h2>1.0 beta 2 (July 16, 2020)</h2><ul><li>Add string tables for non-English languages.</li></ul><h2>1.0 beta 1 (July 15, 2020)</h2><ul><li>Add automatic follower gains for the following interactions: selling a painting or photo, making an app or game, licensing a song or lyrics, publishing a book, being nominated for and accepting an award, completing a work day as an actor, ranking up as a celebrity, and getting positive PR.</li><li>Add automatic follower losses for the following interactions: ranking down as a celebrity and getting bad PR.</li><li>Add debug cheats to quickly increase or decrease your follower count.</li></ul>"}],"translations":[{"code":"ENG_US","translators":[{"name":"Frankk"}]},{"code":"SPA_EA","translators":[{"name":"Diavlo"}]},{"code":"ITA_IT","href":"https://www.patreon.com/posts/67711723","translators":[{"name":"ISY","href":"https://isytranslations.wixsite.com/isystranslations"}]},{"code":"NOR_NO","translators":[{"name":"Susanne"}]},{"code":"POL_PL","translators":[{"name":"Osqar","href":"https://www.patreon.com/osqar"}]},{"code":"POR_BR","translators":[{"name":"Larissa Sousa"}]},{"code":"RUS_RU","translators":[{"name":"dep4ikk"}]},{"code":"CHT_CN","translators":[{"name":"Ttchubb"}]}],"downloads":[{"host":"Sim File Share","href":"http://www.simfileshare.net/download/1930737/"},{"host":"Google Drive","href":"https://drive.google.com/drive/folders/18eZztaSfaTo5PWO3pC1ITgiL8h8jqD9N?usp=sharing"}]}

=== frankkulak/mods-web-data/data/mods/extra-holidays/index.json
{
  "$schema": "../../../schemas/mod.schema.json",
  "name": "Extra Holidays",
  "tagline": "Adds Spookyfest and Flower Day",
  "description": "Tired of manually adding common holidays to the calendar? This mod will make some more of them appear by default.",
  "version": "1.0 beta 3",
  "lastUpdated": "June 12, 2023",
  "stage": "beta",
  "earlyAccess": "beta",
  "publicRelease": "June 14, 2023",
  "status": "working",
  "seoTags": [
    "halloween",
    "spookyfest",
    "easter",
    "flower",
    "holiday",
    "calendar",
    "seasons"
  ],
  "requiredPacks": {
    "eps": [
      "Seasons"
    ]
  },
  "pages": [
    {
      "title": "Details",
      "html": "details.html"
    },
    {
      "title": "Changelog",
      "html": "changelog.html"
    }
  ],
  "translations": [
    {
      "code": "ENG_US",
      "translators": [
        {
          "name": "Frankk"
        }
      ]
    }
  ],
  "downloads": [
    {
      "host": "Patreon",
      "href": "https://www.patreon.com/posts/84235940"
    }
  ],
  "downloadWarning": "You must install the script, but all packages are optional (only install the holidays that you want). To rename a holiday, you can edit the 'HolidayNames.cfg' file with a plain text editor, like Notepad or TextEdit."
}

=== frankkulak/mods-web-data/data/mods/custom-holiday-utility/index.json
{
  "$schema": "../../../schemas/mod.schema.json",
  "name": "Custom Holiday Utility",
  "tagline": "Makes modded holidays behave",
  "description": "Enable modded holidays in existing saves, and get rid of that pesky exception notification caused by uninstalling them.",
  "version": "1.1",
  "lastUpdated": "July 4, 2025",
  "stage": "public",
  "status": "untested",
  "hideTranslations": true,
  "pages": [
    {
      "title": "For Users",
      "html": "users.html"
    },
    {
      "title": "For Modders",
      "html": "modders.html"
    },
    {
      "title": "Changelog",
      "html": "changelog.html"
    }
  ],
  "requiredPacks": {
    "eps": [
      "Seasons"
    ]
  },
  "documentation": [
    {
      "host": "Google Drive",
      "href": "https://drive.google.com/drive/folders/1xZTTfFxA18UMaW-MAu2z45eXo7pvQVrS?usp=sharing"
    }
  ],
  "downloads": [
    {
      "host": "Sim File Share",
      "href": "https://simfileshare.net/folder/191078/"
    },
    {
      "host": "Google Drive",
      "href": "https://drive.google.com/drive/folders/1yY0cSKun1qGyzekXatcngoHhlnTt1Z2M?usp=sharing"
    }
  ]
}

=== frankkulak/mods-web-data/build/mods/festive-milestones.json
{"name":"Festive Milestones","tagline":"Milestones for events and holidays","description":"Your sims should remember their special days. This mod adds milestones for events, festivals, and holidays from various packs.","version":"1.1","lastUpdated":"July 4, 2025","stage":"public","status":"working","seoTags":["festive","festival","event","holiday","developmental","milestone","memories"],"requiredPacks":{"eps":["Growing Together"]},"recommendedPacks":{"eps":["City Living","Island Living","Seasons","Snowy Escape"]},"pages":[{"title":"Details","html":"<h2>Summary</h2><p>This mod adds milestones for all events, festivals, and holidays in <strong>City Living</strong>, <strong>Island Living</strong>, <strong>Seasons</strong>, and <strong>Snowy Escape</strong>.</p><hr><div class=\"paragraphs\"><h2 class=\"mt-4\">City Living</h2><p>There are 5 milestones for the festivals and events that occur in San Myshuno. To get these, you need to be nearby the area while they are happening.</p><div class=\"my-4 flex justify-between flex-wrap gap-4\"><ul><li>GeekCon</li><li>Humor &amp; Hijinks Festival</li><li>Romance Festival</li><li>Spice Festival</li><li>Flea Market</li></ul><img class=\"feature\" data-src=\"city-living-milestones\" alt=\"City Living Milestones\"></div></div><hr><div class=\"paragraphs\"><h2 class=\"mt-4\">Island Living</h2><p>There are 8 milestones for events and festivals that occur in Sulani. To get these, you need to be nearby the area while they are happening.</p><div class=\"my-4 flex justify-between flex-wrap gap-4\"><ul><li>Family Fun Day</li><li>Flowers &amp; Music Festival</li><li>Town BBQ</li><li>Town Potluck</li><li>Island Celebration</li><li>Beach Bonfire</li><li>Fishing Competition</li><li>Turtle Hatching</li></ul><img class=\"feature\" data-src=\"island-living-milestones\" alt=\"Island Living Milestones\"></div></div><hr><div class=\"paragraphs\"><h2 class=\"mt-4\">Seasons</h2><p>There are 8 milestones for holidays and meeting special sims from Seasons. To get the milestone for a holiday, you must complete enough traditions to get at least a silver medal for it. To get the milestones for meeting special sims, you have to talk to them.</p><div class=\"my-4 flex justify-between flex-wrap gap-4\"><ul><li>Flower Day*</li><li>Harvestfest</li><li>Love Day</li><li>New Year's Eve</li><li>Simdependence Day*</li><li>Spookyfest*</li><li>Winterfest</li><li>Meeting Father Winter</li><li>Meeting Flower Bunny</li></ul><img class=\"feature\" data-src=\"seasons-milestones\" alt=\"Seasons Milestones\"></div><p class=\"footnote\">* There are no official \"Flower Day\", \"Simdependence Day\", or \"Spookyfest\" holidays in Seasons; these come from my <a href=\"#/mods/extra-holidays\" target=\"_blank\">Extra Holidays</a> mod, which must also be installed in order for these milestones to work.</p></div><hr><div class=\"paragraphs\"><h2 class=\"mt-4\">Snowy Escape</h2><p>There are 4 milestones for festivals and meeting special sims in Mt. Komorebi. To get the milestones for festivals, you just need to be in the area while the festival is happening. To get the milestone for meeting Yamachan, you have to... meet Yamachan.</p><div class=\"my-4 flex justify-between flex-wrap gap-4\"><ul><li>Festival of Light</li><li>Festival of Snow</li><li>Festival of Youth</li><li>Meeting Yamachan</li></ul><img class=\"feature\" data-src=\"snowy-escape-milestones\" alt=\"Snowy Escape Milestones\"></div></div><hr><div class=\"paragraphs\"><h2>Cheats</h2><p>To add all milestones associated with a pack to the active sim, run <code>fkfm.add_all &lt;pack_code&gt;</code>, where the pack code is one of <code>ep03</code> (City Living), <code>ep05</code> (Seasons), <code>ep07</code> (Island Living), or <code>ep10</code> (Snowy Escape).</p></div><hr><div class=\"paragraphs\"><h2>Known issues</h2><ul><li>Traveling on Love Day with this mod installed may cause an exception. I do not know why this exception occurs, but it does not cause any damage to your save/play session and can be ignored until fixed.</li></ul></div>"},{"title":"Changelog","html":"<div class=\"paragraphs\"><h2>1.1 (July 4, 2025)</h2><ul><li>Fix compatibility issue with 2025-07-01 patch (HasTunableReference deprecation).</li></ul></div><div class=\"paragraphs\"><h2>1.0 (June 27, 2023)</h2><ul><li>Add Russian and Spanish translations</li><li>End beta phase (public release)</li></ul></div><div class=\"paragraphs\"><h2>1.0 beta 3 (June 25, 2023)</h2><ul><li>Add milestone for Simdependence Day (from my <a target=\"_blank\" href=\"#/mods/extra-holidays\">Extra Holidays</a> mod)</li></ul></div><div class=\"paragraphs\"><h2>1.0 beta 2 (June 19, 2023)</h2><ul><li>Make Island Living milestones trigger for attending festival rather than participating</li><li>Fix bug with <code>fkfm.add_all</code> cheat that can double existing milestones</li></ul></div><div class=\"paragraphs\"><h2>1.0 beta 1 (June 13, 2023)</h2><ul><li>Create City Living milestones:</li><ul><li>GeekCon</li><li>Humor &amp; Hijinks Festival</li><li>Romance Festival</li><li>Spice Festival</li><li>Flea Market</li></ul></ul></div><div class=\"paragraphs\"><h2>1.0 alpha 3 (June 12, 2023)</h2><ul><li>Create Seasons milestones:</li><ul><li>Flower Day</li><li>Harvestfest</li><li>Love Day</li><li>New Year's Eve</li><li>Spookyfest</li><li>Winterfest</li><li>Meeting Father Winter</li><li>Meeting Flower Bunny</li></ul></ul></div><div class=\"paragraphs\"><h2>1.0 alpha 2 (June 10, 2023)</h2><ul><li>Add safeguard to ensure festival is running when milestone is given</li><li>Change all milestones from \"Life\" to \"Firsts\"</li><li>Rename Island Living milestones to be more Maxis-match</li><li>Create Snowy Escape milestones:</li><ul><li>Festival of Light</li><li>Festival of Snow</li><li>Festival of Youth</li><li>Met Yamachan</li></ul></ul></div><div class=\"paragraphs\"><h2>1.0 alpha 1 (June 7, 2023)</h2><ul><li>Create Island Living milestones:</li><ul><li>Beach Bonfire</li><li>Family Fun Day</li><li>Fishing Competition</li><li>Flowers &amp; Music Festival</li><li>Island Celebration</li><li>Town BBQ</li><li>Town Potluck</li><li>Turtle Hatching</li></ul></ul></div>"}],"translations":[{"code":"ENG_US","translators":[{"name":"Frankk"}]},{"code":"RUS_RU","translators":[{"name":"Ciri"}]},{"code":"SPA_EA","outdated":true,"translators":[{"name":"Juliet26"}]},{"code":"FRE_FR","href":"https://modsims4.fr/divers/mods-etapes-de-vie-pour-vos-sims/#frankk","translators":[{"name":"Kimikosoma"}]},{"code":"CHT_CN","href":"https://www.patreon.com/posts/festive-jie-ri-88706919","translators":[{"name":"MeowCats"}]}],"downloads":[{"host":"SimFileShare","href":"https://simfileshare.net/download/3980085/"},{"host":"Google Drive","href":"https://drive.google.com/drive/folders/1tL7rotY72S3tyL44q9zXZSeowD7C9gvm?usp=drive_link"}],"downloadWarning":"You must install the script, but all packages are optional. Only install packages for packs that you own and want in your game. Playing with packages for packs that you do not own can and will cause issues."}

=== frankkulak/mods-web-data/build/mods/no-discovery-quests.json
{"name":"No Discovery Quests","tagline":"I know how to play this game","description":"Prevents \"Discovery Quest\" popups from ever bothering you again.","version":"1.0","lastUpdated":"February 14, 2024","stage":"public","status":"untested","hasNoCustomStrings":true,"seoTags":["discovery","quest","silence","phone","notification"],"pages":[{"title":"Details","html":"<div class=\"paragraphs\"><h2>What does this mod do?</h2><p>It silences \"Discovery Quest\" phone calls and notifications. That's it.</p><h2>Isn't this in my game settings?</h2><p>Yes, but it does not prevent popups that have already been scheduled.</p><p class=\"footnote\">Your existing save(s) likely already have quite a few of these.</p><p>This mod has two advantages over the setting:</p><ul><li>It silences Discovery Quests by default, in every save</li><li>It works on Discovery Quests that have already been scheduled</li></ul><h2>Known issues</h2><ul><li>This mod also silences Reaper's Rewards popups, as they are implemented as Discovery Quests.</li></ul></div>"},{"title":"Changelog","html":"<h2>1.0 (February 14, 2024)</h2><ul><li>Initial release.</li></ul>"}],"downloads":[{"host":"Sim File Share","href":"http://www.simfileshare.net/download/4470810/"},{"host":"Google Drive","href":"https://drive.google.com/file/d/1JES8KGjW8nwvQs7oS3afO_SvD1XMR-TA/view?usp=drive_link"}]}
