=== frankkulak/mods-web-data/schemas/mod.schema.json
{
  "$schema": "http://json-schema.org/schema",
  "definitions": {
    "downloadList": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "host",
          "href"
        ],
        "properties": {
          "host": {
            "description": "Name of website where download is hosted.",
            "type": "string"
          },
          "href": {
            "description": "HREF to use in download link.",
            "type": "string"
          }
        }
      }
    },
    "expansionPacks": {
      "type": "string",
      "enum": [
        "Get to Work",
        "Get Together",
        "City Living",
        "Cats & Dogs",
        "Seasons",
        "Get Famous",
        "Island Living",
        "Discover University",
        "Eco Lifestyle",
        "Snowy Escape",
        "Cottage Living",
        "High School Years",
        "Growing Together",
        "For Rent",
        "Life & Death",
        "Businesses & Hobbies",
        "Enchanted by Nature",
        "Adventure Awaits",
        "Royalty & Legacy"
      ]
    },
    "gamePacks": {
      "type": "string",
      "enum": [
        "Outdoor Retreat",
        "Spa Day",
        "Dine Out",
        "Vampires",
        "Parenthood",
        "Jungle Adventure",
        "Strangerville",
        "Realm of Magic",
        "Journey to Batuu",
        "Dream Home Decorator",
        "My Wedding Stories",
        "Werewolves"
      ]
    },
    "stuffPacks": {
      "type": "string",
      "enum": [
        "Luxury Party Stuff",
        "Perfect Patio Stuff",
        "Cool Kitchen Stuff",
        "Spooky Stuff",
        "Movie Hangout Stuff",
        "Romantic Garden Stuff",
        "Kids Room Stuff",
        "Backyard Stuff",
        "Vintage Glamour Stuff",
        "Bowling Night Stuff",
        "Fitness Stuff",
        "Toddler Stuff",
        "Laundry Day Stuff",
        "My First Pet Stuff",
        "Moschino Stuff",
        "Tiny Living Stuff",
        "Nifty Knitting Stuff",
        "Paranormal Stuff"
      ]
    },
    "kitPacks": {
      "type": "string",
      "enum": [
        "Throwback Fit Kit",
        "Country Kitchen Kit",
        "Bust the Dust Kit",
        "Courtyard Oasis Kit",
        "Fashion Street Kit",
        "Industrial Loft Stuff",
        "Incheon Arrivals Kit",
        "Modern Menswear Kit",
        "Blooming Rooms Kit",
        "Carnaval Streetwear Kit",
        "Decor to the Max Kit",
        "Moonlight Chic Kit",
        "Little Campers Kit",
        "First Fits Kit",
        "Desert Luxe Kit",
        "Pastel Pop Kit",
        "Everyday Clutter Kit",
        "Simtimates Collection Kit",
        "Bathroom Clutter Kit",
        "Greenhouse Haven Kit",
        "Basement Treasures Kit"
      ]
    },
    "packs": {
      "type": "object",
      "properties": {
        "eps": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/expansionPacks"
          }
        },
        "gps": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/gamePacks"
          }
        },
        "sps": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/stuffPacks"
          }
        },
        "kits": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/kitPacks"
          }
        }
      }
    }
  },
  "type": "object",
  "required": [
    "description",
    "name",
    "pages",
    "stage",
    "status",
    "tagline"
  ],
  "properties": {
    "skipIndex": {
      "description": "If true, then don't list this mod in the index.",
      "type": "boolean"
    },
    "description": {
      "description": "Brief description of this mod.",
      "type": "string"
    },
    "documentation": {
      "description": "List of places to download the documentation.",
      "$ref": "#/definitions/downloadList"
    },
    "downloads": {
      "description": "List of places to download the mod.",
      "$ref": "#/definitions/downloadList"
    },
    "downloadWarning": {
      "description": "HTML content to display while downloading the mod.",
      "type": "string"
    },
    "earlyAccess": {
      "description": "What kind of early access this mod is in, if any.",
      "type": "string",
      "enum": [
        "alpha",
        "beta",
        "none"
      ]
    },
    "featured": {
      "description": "Whether or not this mod should be displayed more prominently.",
      "type": "boolean"
    },
    "hasNoCustomStrings": {
      "description": "Whether or not this mod has no custom strings (intentionally negated so default can be false).",
      "type": "boolean"
    },
    "hideTranslations": {
      "description": "Whether or not to hide the translations section.",
      "type": "boolean"
    },
    "lastUpdated": {
      "description": "The date of the last update to this mod.",
      "type": "string"
    },
    "name": {
      "description": "Display name of this mod.",
      "type": "string"
    },
    "notTranslatable": {
      "description": "Whether or not this mod cannot be translated (intentionally negated so default can be false).",
      "type": "boolean"
    },
    "pages": {
      "description": "List of pages to display for this mod.",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "title",
          "html"
        ],
        "properties": {
          "title": {
            "description": "Label to display on the tab for this page.",
            "type": "string"
          },
          "html": {
            "description": "Name of HTML file to use for this page's content.",
            "type": "string"
          }
        }
      }
    },
    "publicRelease": {
      "description": "The date this mod goes public.",
      "type": "string"
    },
    "recommendedPacks": {
      "description": "Packs that enhance this mod's gameplay.",
      "$ref": "#/definitions/packs"
    },
    "requiredPacks": {
      "description": "Packs that are required for this mod to work. If empty, it is BG compatible.",
      "$ref": "#/definitions/packs"
    },
    "seoTags": {
      "description": "Tags to use for SEO with this mod.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "stage": {
      "description": "Current development stage of this mod.",
      "type": "string",
      "enum": [
        "alpha",
        "beta",
        "public",
        "wip"
      ]
    },
    "status": {
      "description": "The current status of this mod.",
      "type": "string",
      "enum": [
        "broken",
        "unreleased",
        "untested",
        "working"
      ]
    },
    "tagline": {
      "description": "Very brief text to display under mod name.",
      "type": "string"
    },
    "translations": {
      "description": "List of available translations.",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "code",
          "translators"
        ],
        "properties": {
          "code": {
            "description": "The code for this locale.",
            "type": "string",
            "enum": [
              "ENG_US",
              "CHS_CN",
              "CHT_CN",
              "CZE_CZ",
              "DAN_DK",
              "DUT_NL",
              "FIN_FI",
              "FRE_FR",
              "GER_DE",
              "ITA_IT",
              "JPN_JP",
              "KOR_KR",
              "NOR_NO",
              "POL_PL",
              "POR_BR",
              "RUS_RU",
              "SPA_EA",
              "SWE_SE"
            ]
          },
          "href": {
            "description": "Link to mod, if it's not included in download.",
            "type": "string"
          },
          "translators": {
            "description": "List of people who contributed to this translation.",
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "name"
              ],
              "properties": {
                "name": {
                  "description": "Name of translator.",
                  "type": "string"
                },
                "href": {
                  "description": "Optional link to this translator's web page.",
                  "type": "string"
                }
              }
            }
          },
          "outdated": {
            "description": "Whether or not this translation is outdated.",
            "type": "boolean"
          }
        }
      }
    },
    "version": {
      "description": "Current version of the mod.",
      "type": "string"
    },
    "videos": {
      "description": "List of videos showcasing the mod.",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "creator",
          "name",
          "platform",
          "href"
        ],
        "properties": {
          "creator": {
            "description": "Who made the video.",
            "type": "string"
          },
          "href": {
            "description": "Link where the video can be found.",
            "type": "string"
          },
          "name": {
            "description": "Name of the video.",
            "type": "string"
          },
          "platform": {
            "description": "Where the video is posted.",
            "type": "string"
          }
        }
      }
    }
  }
}

=== frankkulak/mods-web-data/build/mods/extra-holidays.json
{"name":"Extra Holidays","tagline":"Adds more default holidays","description":"Tired of manually adding common holidays to the calendar? This mod will make some more of them appear by default.","version":"1.0","lastUpdated":"June 18, 2023","stage":"public","status":"untested","seoTags":["halloween","spookyfest","easter","flower","4th of july","fourth of july","independece","simdependence","day","holiday","calendar","seasons"],"requiredPacks":{"eps":["Seasons"]},"pages":[{"title":"Details","html":"<div class=\"paragraphs\"><h2>Summary</h2><p>This mod adds three new holidays: \"Spookyfest\", \"Flower Day\", and \"Simdependence Day\". They are each in their own package, so only install the one(s) you want.</p></div><div class=\"paragraphs\"><h2 class=\"danger\">Important Notices</h2><p>This mod requires my <a target=\"_blank\" href=\"#/mods/custom-holiday-utility\">Custom Holiday Utility</a> mod. You must install it as well, or none of these holidays will work.</p><p>If you want these holidays to appear in an existing save, you must run the cheat <code>chu.add_missing_holidays</code>.</p></div><hr><div class=\"paragraphs\"><h2>Spookyfest</h2><div class=\"collapse-split-view\"><div><p>Occurs during Fall. Does NOT come with a day off from work and school.</p><h4 class=\"mt-4\">Schedule</h4><ul><li>7 day seasons &rarr; Monday of week 1</li><li>14 day seasons &rarr; Friday of week 1</li><li>28 day seasons &rarr; Friday of week 3</li></ul></div><img class=\"feature\" style=\"width: 256px\" data-src=\"spookyfest\" alt=\"Spookyfest Traditions\"></div></div><hr><div class=\"paragraphs\"><h2>Flower Day</h2><div class=\"collapse-split-view\"><div><p>Occurs during Spring. Comes with a day off from work and school.</p><h4 class=\"mt-4\">Schedule</h4><ul><li>7 day seasons &rarr; Monday of week 1</li><li>14 day seasons &rarr; Monday of week 1</li><li>28 day seasons &rarr; Monday of week 2</li></ul><p class=\"mt-4 footnote\">Though it is based on Easter, Monday was chosen instead of Sunday because (1) Sunday holidays do not work when you start in that season, (2) being on Sunday would put Flower Day on New Year's Day, and (3) this way you can have the day after off of work and school.</p></div><img class=\"feature\" style=\"width: 256px\" data-src=\"flower-day\" alt=\"Flower Day Traditions\"></div></div><hr><div class=\"paragraphs\"><h2>Simdependence Day</h2><div class=\"collapse-split-view\"><div><p>Occurs during Summer. Comes with a day off from work and school.</p><h4 class=\"mt-4\">Schedule</h4><ul><li>7 day seasons &rarr; Wednesday of week 1</li><li>14 day seasons &rarr; Wednesday of week 1</li><li>28 day seasons &rarr; Wednesday of week 2</li></ul></div><img class=\"feature\" style=\"width: 256px\" data-src=\"simdependence-day\" alt=\"Simdependence Day Traditions\"></div></div>"},{"title":"Changelog","html":"<div class=\"paragraphs\"><h2>1.0 (June 18, 2023)</h2><ul><li>Refactor holidays to use <a target=\"_blank\" href=\"#/mods/custom-holiday-utility\">Custom Holiday Utility</a></li><li>Remove ability to rename holidays</li><li>Add Simdependence Day</li></ul></div><div class=\"paragraphs\"><h2>June 14, 2023</h2><ul><li>Unpublish mod with warning</li></ul></div><div class=\"paragraphs\"><h2>1.0 beta 3 (June 12, 2023)</h2><ul><li>Rename mod from \"Halloween Holiday\" to \"Extra Holidays\"</li><li>Rename \"Halloween\" to \"Spookyfest\" by default</li><li>Add \"Wear Costumes\" to Spookyfest traditions</li><li>Add \"Flower Day\" holiday (based on Easter)</li><li>Rename <code>HolidayNameOverride.txt</code> to <code>HolidayNames.cfg</code></li><li>Remove debug cheats since they didn't even work :)</li></ul></div><div class=\"paragraphs\"><h2>1.0 beta 2 (June 8, 2023)</h2><ul><li>Add <code>HolidayNameOverride.txt</code> to customize holiday name</li></ul></div><div class=\"paragraphs\"><h2>1.0 beta 1 (June 7, 2023)</h2><ul><li>Add default Halloween holiday</li><li>Add debug cheat to start Halloween</li></ul></div>"}],"translations":[{"code":"ENG_US","translators":[{"name":"Frankk"}]}],"downloads":[{"host":"Sim File Share","href":"https://simfileshare.net/folder/190842/"},{"host":"Google Drive","href":"https://drive.google.com/drive/folders/1rPBxN6Gr2SxbUMGcDKZ36IeG7svFTuMW?usp=sharing"}],"downloadWarning":"This mod requires my <a class=\"text-gray-800 dark:text-yellow-800\" target=\"_blank\" href=\"#/mods/custom-holiday-utility\">Custom Holiday Utility</a> mod. You must install it as well, or none of these holidays will work. Each holiday is a standalone mod, so just install the ones you want."}

=== frankkulak/mods-web-data/build/mods/simway.json
{"name":"Simway (MLM Mod)","tagline":"Be your own girlboss","description":"How would you like to be your own boss and set your own hours? Join one of three MLMs, peddle their products, throw selling parties, and recruit others to make a profit!","stage":"wip","status":"unreleased","hideTranslations":true,"seoTags":["multi","level","marketing","network","sales","consultant","pyramid","scheme","plumbonne","llamaware"],"pages":[{"title":"Details","html":"<p class=\"danger text-sm\">\"Simway\" has been a work-in-progress for <em>years</em>, and has been paused while I focus on other things, such as <a href=\"https://sims4toolkit.com\" target=\"_blank\">Sims 4 Toolkit</a>. I am pleased to announce it it now back in full-swing development, and is my primary focus. There is no estimated release date at this time.</p><div class=\"paragraphs\"><h2>Planned features</h2><ul><li>At least three different MLMs for your sims to be a part of.</li><li>You may be approached by MLM members who want to sell products or recruit you.</li><li>You can earn money by selling products or recruiting other sims.</li><li>You have to pay a startup fee to join an MLM and a portion of your profits to remain in it. Want out? Have fun with that :)</li><li>Host and attend \"selling parties\" for custom MLM products.</li></ul></div><div class=\"simway-logos-wrapper\"><img data-src=\"simway-logo\"> <img data-src=\"plumbonne-logo\"> <img data-src=\"llamaware-logo\"></div><style>.simway-logos-wrapper {\n    width: 100%;\n    display: flex;\n    flex-wrap: wrap;\n    gap: 1rem;\n    justify-content: center;\n  }\n\n  .simway-logos-wrapper img {\n    max-width: 300px;\n    -webkit-filter: drop-shadow(2px 2px 2px var(--color-shadow));\n    filter: drop-shadow(2px 2px 2px var(--color-shadow));\n  }</style>"}]}

=== frankkulak/mods-web-data/data/mods/no-lot-taxes/index.json
{
  "$schema": "../../../schemas/mod.schema.json",
  "name": "No Lot Taxes",
  "tagline": "ยง0 property taxes",
  "description": "No taxation without repre- actually, just no taxes. This mod gets rid of property taxes.",
  "version": "1.0",
  "lastUpdated": "February 3, 2024",
  "stage": "public",
  "status": "working",
  "hasNoCustomStrings": true,
  "seoTags": [
    "tax",
    "taxes",
    "brackets",
    "bills"
  ],
  "pages": [
    {
      "title": "Details",
      "html": "details.html"
    },
    {
      "title": "Changelog",
      "html": "changelog.html"
    }
  ],
  "downloadWarning": "It is not recommended to use this mod with any other mods that affect the billing system, such as SNB by SimRealist.",
  "downloads": [
    {
      "host": "Sim File Share",
      "href": "http://www.simfileshare.net/download/4447951/"
    },
    {
      "host": "Google Drive",
      "href": "https://drive.google.com/drive/folders/1GcMEiNTMe9Ro_lejHQ-8o0_z7-s7oJ0Y?usp=drive_link"
    }
  ]
}

=== frankkulak/mods-web-data/build/mods/online-homework.json
{"name":"Online Homework","tagline":"Do homework on computers","description":"Can't find your sim's notebook? Well, now you can do their homework at any computer or laptop. This mod works for children, teens, and university students.","version":"1.1.1","lastUpdated":"March 6, 2024","stage":"public","status":"working","hasNoCustomStrings":true,"seoTags":["kids","school","interaction"],"recommendedPacks":{"eps":["Discover University"]},"pages":[{"title":"Details","html":"<h2>How to use</h2><div class=\"paragraphs\"><p>Click on any computer (including most CC) to do homework.</p><ul><li><span class=\"font-bold\">Children/Teens</span>: Select the \"Do Homework\" interaction.</li><li><span class=\"font-bold\">University Students</span>: Go to the \"University > University Coursework\" menu, and then select the \"Do Homework\" interaction.</li><p class=\"footnote\">University homework requires the Discover University expansion pack.</p></ul></div><h2>Don't have Discover University?</h2><p>No worries. You can still use this mod with the base game - it'll just ignore the university files.</p>"},{"title":"Changelog","html":"<h2>1.1.1 (March 6, 2024)</h2><ul><li>Consolidate packages for easier installation</li><li>Clean up script to avoid conflicts for users with many script mods</li></ul><h2>1.1 (December 21, 2020)</h2><ul><li>Remove custom strings so that all languages are supported.</li><li>Add online homework for children and teens.</li></ul><h2>1.0.4 (November 15, 2020)</h2><ul><li>Add Polish translation (by Osqar).</li></ul><h2>1.0.3 (October 21, 2020)</h2><ul><li>Add Chinese translation (by MuMu).</li></ul><h2>1.0.2 (October 7, 2020)</h2><ul><li>Add French translation (by Kimikosoma).</li></ul><h2>1.0.1 (October 6, 2020)</h2><ul><li>Fix issue where Italian text showed up in the English version.</li></ul><h2>1.0 (October 6, 2020)</h2><ul><li>Add the ability to do university homework at any computer or laptop.</li></ul>"}],"downloads":[{"host":"Sim File Share","href":"http://www.simfileshare.net/download/2089628/"},{"host":"Google Drive","href":"https://drive.google.com/drive/folders/1GKkgjuWfSklSN7_cN2p0JJsbkF39eKhF?usp=sharing"}]}

=== frankkulak/mods-web-data/build/mods/bunpocalypse.json
{"name":"Bunpocalypse","tagline":"You want bunnies, you get bunnies","description":"Go ahead, try to escape the bunnies. I dare you.","version":"1.0","lastUpdated":"April 1, 2023","stage":"public","status":"untested","hasNoCustomStrings":true,"seoTags":["bunny","rabbit","chaos","funny","weird"],"pages":[{"title":"Details","html":"<h2>What to expect</h2><ul><li>Bunnies. So many bunnies.</li><li>Big bunnies. Small bunnies. Bunnies that <span class=\"text-subtle\" title=\"REDACTED\">&#9608;&#9608;&#9608;&#9608;</span>.</li></ul><br><div class=\"images-md\"><img data-src=\"staring\"> <img data-src=\"running\"> <img data-src=\"pancakes\"></div><h2>Things you definitely should \"not\" do</h2><div class=\"paragraphs\"><p>Doing these things will cause bunnies to <span class=\"text-subtle\" title=\"REDACTED\">&#9608;&#9608;&#9608;&#9608;</span>.</p><ul><li>Leave bunnies in the rain.</li><li>Bring bunnies in the vicinity of foxes.</li><li>Let bunnies help with gardening.</li><li>Wait for bunnies to give you gifts.</li></ul></div><h2>Not enough bunnies??? Use cheats!</h2><div class=\"paragraphs\"><ul><li><code>spawn_rabbit &lt;count&gt;</code> &rarr; Spawns rabbit(s) on the active sim</li><li><code>spawn_rabbit_all &lt;count&gt;</code> &rarr; Spawns rabbit(s) on every sim in the world</li></ul><p class=\"footnote mt-2\">Replace <code>&lt;count&gt;</code> with the number of rabbits to spawn. If omitted, defaults to 1.</p></div><h2>Warnings & known issues</h2><ul><li>Bunnies.</li><li>You may see animation exceptions if you use MCCC/BE with this mod.</li><li>More bunnies.</li></ul><br><div class=\"paragraphs\"><p class=\"text-sm text-subtle\">This mod was made in collaboration with <a href=\"https://chippeds-creation-corner.super.site/\" target=\"_blank\">ChippedSim</a>, who wrote most of the tuning. Since you guys <strong class=\"text-subtle\">REALLY</strong> seem to love bunnies, we decided to bring you <em class=\"text-subtle font-bold\">some</em>.</p><p class=\"text-sm danger\">Now, stop asking her about bunnies. You got them right here.</p></div>"},{"title":"Changelog","html":"<h2>1.0 (April 1, 2023)</h2><ul><li>April fools.</li></ul>"}],"downloadWarning":"Please look at the date this mod was posted, and don't take it too seriously. Also, you probably shouldn't save your game while using this mod.","downloads":[{"host":"Google Drive","href":"https://drive.google.com/file/d/1VJnEqq4MYueiI3tBl930x_CW3OHDTKLR/view?usp=share_link"}],"requiredPacks":{"eps":["Cottage Living"]},"hideTranslations":true}

=== frankkulak/mods-web-data/data/mods/pack-tests/index.json
{
  "$schema": "../../../schemas/mod.schema.json",
  "name": "Pack Tests",
  "tagline": "Utility for modders",
  "description": "If you ever need to test whether your users have a particular pack installed or not, this script will allow you to do so directly in tuning - no scripting abilities required!",
  "version": "1.0.1",
  "lastUpdated": "July 20, 2021",
  "stage": "public",
  "status": "untested",
  "hideTranslations": true,
  "pages": [
    {
      "title": "For Users",
      "html": "users.html"
    },
    {
      "title": "For Modders",
      "html": "modders.html"
    },
    {
      "title": "Changelog",
      "html": "changelog.html"
    }
  ],
  "documentation": [
    {
      "host": "Sim File Share",
      "href": "http://www.simfileshare.net/download/2251516/"
    }
  ],
  "downloads": [
    {
      "host": "Sim File Share",
      "href": "http://www.simfileshare.net/download/2251515/"
    },
    {
      "host": "Google Drive",
      "href": "https://drive.google.com/drive/folders/19Xw1Yt1FEvT2AzZmnq7dYwe6ImgDZKiv?usp=sharing"
    }
  ]
}

=== frankkulak/mods-web-data/build/mods/show-sim-info.json
{"name":"Show Sim Info","tagline":"View internal sim data","description":"View all of the internal data for particular sims with an interaction. Originally by Itasan on MTS.","version":"3.8.10","lastUpdated":"September 6, 2025","stage":"public","status":"untested","hideTranslations":true,"pages":[{"title":"Details","html":"<h2>What does this mod do?</h2><div class=\"paragraphs\"><p>It allows you to view the internal data associated with your sims.</p><p>For screenshots and more in-depth details, please visit the <a href=\"https://modthesims.info/d/576053/show-search-sim-info-mod.html\" target=\"_blank\">original page by Itasan on MTS</a>.</p></div><h2>Why is this mod on this website?</h2><p>Show Sim Info broke after the July 26, 2022 patch for the High School Years pack, and its original creator, Itasan, no longer updates it. This is a very important mod for many modders and players, so I fixed it myself and wanted to share it with others.</p><h2>Known issues</h2><ul><li>Hidden buffs may appear as \"Buff\", rather than their proper name.</li></ul><br><p><span class=\"danger\">Please ensure you have deleted Ita's version of this mod (the one from Mod The Sims)</span>, and <a href=\"#/contact\">let me know</a> if you experience any issues with my version.</p><br><p class=\"text-subtle\"><span class=\"font-bold text-subtle\">To Itasan</span>: I assumed that you would be alright with someone else maintaining your mod because you have not been active in a couple of years. If this is not the case, please reach out to me and I will remove it from my website.</p>"},{"title":"Changelog","html":"<h2>3.8.10 (September 6, 2025)</h2><ul><li>Fix issue with August 19, 2025 patch that prevented households from loading</li></ul><h2>3.8.9 (March 6, 2024)</h2><ul><li>Fix issues for Crystal Creations patch</li></ul><h2>3.8.8 (December 5, 2023)</h2><ul><li>Fix issues after For Rent patch</li></ul><h2>3.8.7 (August 17, 2023)</h2><ul><li>Display sim pronouns in the \"This Sim\" panel</li><li>Fix issue where filtering by relationship only filtered by gender</li><li>Fix some English typos</li></ul><h2>3.8.6 (July 23, 2023)</h2><ul><li>Add support for horses</li><li>Fix issue with displaying info for foxes</li></ul><h2>3.8.5 (May 23, 2023)</h2><ul><li>Fix issue with displaying career history</li><p class=\"footnote\">This fixes a common issue with retired sims' career panels</p></ul><h2>3.8.4 (March 18, 2023)</h2><ul><li>Add compatibility with infants</li><li>Add compatibility for missing occult types (mermaid, werewolf, spellcaster, and plant sims)</li><li>Add compatibility for missing species (fox)</li></ul><h2>3.8.3 (August 7, 2022)</h2><ul><li>Fix issues with displaying age &amp; career data</li><li>Fix issues with using cheats</li><li>Fix issues with outputting to text file</li></ul><h2>3.8.2 (July 27, 2022)</h2><ul><li>Adopt this mod from <a href=\"https://modthesims.info/d/576053/show-search-sim-info-mod.html\" target=\"_blank\">Itasan</a></li><li>Fix issue from the High School Years patch (the \"This Sim\" interaction)</li></ul>"}],"downloadWarning":"If you have downloaded this mod from Mod The Sims, delete that version before installing this one. Note that using a cloud service (OneDrive, Google Drive, iCloud, etc.) to back up your Mods folder can cause files to stick around even after you think you've deleted them.","downloads":[{"host":"Sim File Share","href":"http://simfileshare.net/folder/167469/"},{"host":"Google Drive","href":"https://drive.google.com/drive/folders/1LysKnKrwf_dkunwtNRuBnDa81p0WeGX-?usp=sharing"}]}

=== frankkulak/mods-web-data/data/mods/custom-holiday-fix/index.json
{
  "$schema": "../../../schemas/mod.schema.json",
  "name": "Custom Holiday Fix",
  "tagline": "Makes custom holidays behave",
  "description": "Enable custom holidays in existing saves, and get rid of that pesky exception notification caused by uninstalling them.",
  "version": "1.0",
  "lastUpdated": "June 15, 2023",
  "stage": "wip",
  "status": "unreleased",
  "hideTranslations": true,
  "pages": [
    {
      "title": "For Users",
      "html": "users.html"
    },
    {
      "title": "For Modders",
      "html": "modders.html"
    },
    {
      "title": "Changelog",
      "html": "changelog.html"
    }
  ],
  "requiredPacks": {
    "eps": [
      "Seasons"
    ]
  }
}
