=== frankkulak/mods-web-data/schemas/mod.schema.json
{
  "$schema": "http://json-schema.org/schema",
  "definitions": {
    "downloadList": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "host",
          "href"
        ],
        "properties": {
          "host": {
            "description": "Name of website where download is hosted.",
            "type": "string"
          },
          "href": {
            "description": "HREF to use in download link.",
            "type": "string"
          }
        }
      }
    },
    "expansionPacks": {
      "type": "string",
      "enum": [
        "Get to Work",
        "Get Together",
        "City Living",
        "Cats & Dogs",
        "Seasons",
        "Get Famous",
        "Island Living",
        "Discover University",
        "Eco Lifestyle",
        "Snowy Escape",
        "Cottage Living",
        "High School Years",
        "Growing Together",
        "For Rent",
        "Life & Death",
        "Businesses & Hobbies",
        "Enchanted by Nature",
        "Adventure Awaits",
        "Royalty & Legacy"
      ]
    },
    "gamePacks": {
      "type": "string",
      "enum": [
        "Outdoor Retreat",
        "Spa Day",
        "Dine Out",
        "Vampires",
        "Parenthood",
        "Jungle Adventure",
        "Strangerville",
        "Realm of Magic",
        "Journey to Batuu",
        "Dream Home Decorator",
        "My Wedding Stories",
        "Werewolves"
      ]
    },
    "stuffPacks": {
      "type": "string",
      "enum": [
        "Luxury Party Stuff",
        "Perfect Patio Stuff",
        "Cool Kitchen Stuff",
        "Spooky Stuff",
        "Movie Hangout Stuff",
        "Romantic Garden Stuff",
        "Kids Room Stuff",
        "Backyard Stuff",
        "Vintage Glamour Stuff",
        "Bowling Night Stuff",
        "Fitness Stuff",
        "Toddler Stuff",
        "Laundry Day Stuff",
        "My First Pet Stuff",
        "Moschino Stuff",
        "Tiny Living Stuff",
        "Nifty Knitting Stuff",
        "Paranormal Stuff"
      ]
    },
    "kitPacks": {
      "type": "string",
      "enum": [
        "Throwback Fit Kit",
        "Country Kitchen Kit",
        "Bust the Dust Kit",
        "Courtyard Oasis Kit",
        "Fashion Street Kit",
        "Industrial Loft Stuff",
        "Incheon Arrivals Kit",
        "Modern Menswear Kit",
        "Blooming Rooms Kit",
        "Carnaval Streetwear Kit",
        "Decor to the Max Kit",
        "Moonlight Chic Kit",
        "Little Campers Kit",
        "First Fits Kit",
        "Desert Luxe Kit",
        "Pastel Pop Kit",
        "Everyday Clutter Kit",
        "Simtimates Collection Kit",
        "Bathroom Clutter Kit",
        "Greenhouse Haven Kit",
        "Basement Treasures Kit"
      ]
    },
    "packs": {
      "type": "object",
      "properties": {
        "eps": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/expansionPacks"
          }
        },
        "gps": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/gamePacks"
          }
        },
        "sps": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/stuffPacks"
          }
        },
        "kits": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/kitPacks"
          }
        }
      }
    }
  },
  "type": "object",
  "required": [
    "description",
    "name",
    "pages",
    "stage",
    "status",
    "tagline"
  ],
  "properties": {
    "skipIndex": {
      "description": "If true, then don't list this mod in the index.",
      "type": "boolean"
    },
    "description": {
      "description": "Brief description of this mod.",
      "type": "string"
    },
    "documentation": {
      "description": "List of places to download the documentation.",
      "$ref": "#/definitions/downloadList"
    },
    "downloads": {
      "description": "List of places to download the mod.",
      "$ref": "#/definitions/downloadList"
    },
    "downloadWarning": {
      "description": "HTML content to display while downloading the mod.",
      "type": "string"
    },
    "earlyAccess": {
      "description": "What kind of early access this mod is in, if any.",
      "type": "string",
      "enum": [
        "alpha",
        "beta",
        "none"
      ]
    },
    "featured": {
      "description": "Whether or not this mod should be displayed more prominently.",
      "type": "boolean"
    },
    "hasNoCustomStrings": {
      "description": "Whether or not this mod has no custom strings (intentionally negated so default can be false).",
      "type": "boolean"
    },
    "hideTranslations": {
      "description": "Whether or not to hide the translations section.",
      "type": "boolean"
    },
    "lastUpdated": {
      "description": "The date of the last update to this mod.",
      "type": "string"
    },
    "name": {
      "description": "Display name of this mod.",
      "type": "string"
    },
    "notTranslatable": {
      "description": "Whether or not this mod cannot be translated (intentionally negated so default can be false).",
      "type": "boolean"
    },
    "pages": {
      "description": "List of pages to display for this mod.",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "title",
          "html"
        ],
        "properties": {
          "title": {
            "description": "Label to display on the tab for this page.",
            "type": "string"
          },
          "html": {
            "description": "Name of HTML file to use for this page's content.",
            "type": "string"
          }
        }
      }
    },
    "publicRelease": {
      "description": "The date this mod goes public.",
      "type": "string"
    },
    "recommendedPacks": {
      "description": "Packs that enhance this mod's gameplay.",
      "$ref": "#/definitions/packs"
    },
    "requiredPacks": {
      "description": "Packs that are required for this mod to work. If empty, it is BG compatible.",
      "$ref": "#/definitions/packs"
    },
    "seoTags": {
      "description": "Tags to use for SEO with this mod.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "stage": {
      "description": "Current development stage of this mod.",
      "type": "string",
      "enum": [
        "alpha",
        "beta",
        "public",
        "wip"
      ]
    },
    "status": {
      "description": "The current status of this mod.",
      "type": "string",
      "enum": [
        "broken",
        "unreleased",
        "untested",
        "working"
      ]
    },
    "tagline": {
      "description": "Very brief text to display under mod name.",
      "type": "string"
    },
    "translations": {
      "description": "List of available translations.",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "code",
          "translators"
        ],
        "properties": {
          "code": {
            "description": "The code for this locale.",
            "type": "string",
            "enum": [
              "ENG_US",
              "CHS_CN",
              "CHT_CN",
              "CZE_CZ",
              "DAN_DK",
              "DUT_NL",
              "FIN_FI",
              "FRE_FR",
              "GER_DE",
              "ITA_IT",
              "JPN_JP",
              "KOR_KR",
              "NOR_NO",
              "POL_PL",
              "POR_BR",
              "RUS_RU",
              "SPA_EA",
              "SWE_SE"
            ]
          },
          "href": {
            "description": "Link to mod, if it's not included in download.",
            "type": "string"
          },
          "translators": {
            "description": "List of people who contributed to this translation.",
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "name"
              ],
              "properties": {
                "name": {
                  "description": "Name of translator.",
                  "type": "string"
                },
                "href": {
                  "description": "Optional link to this translator's web page.",
                  "type": "string"
                }
              }
            }
          },
          "outdated": {
            "description": "Whether or not this translation is outdated.",
            "type": "boolean"
          }
        }
      }
    },
    "version": {
      "description": "Current version of the mod.",
      "type": "string"
    },
    "videos": {
      "description": "List of videos showcasing the mod.",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "creator",
          "name",
          "platform",
          "href"
        ],
        "properties": {
          "creator": {
            "description": "Who made the video.",
            "type": "string"
          },
          "href": {
            "description": "Link where the video can be found.",
            "type": "string"
          },
          "name": {
            "description": "Name of the video.",
            "type": "string"
          },
          "platform": {
            "description": "Where the video is posted.",
            "type": "string"
          }
        }
      }
    }
  }
}

=== frankkulak/mods-web-data/build/mods/halloween-holiday.json
{"name":"Halloween Holiday","tagline":"Adds Halloween to the calendar","description":"This mod page has been moved. See details for link.","version":"N/A","lastUpdated":"N/A","earlyAccess":"beta","stage":"beta","status":"working","seoTags":[],"pages":[{"title":"Details","html":"<p>This mod has been replaced by the <a href=\"#/mods/extra-holidays\">Extra Holidays</a> mod, which includes multiple holidays rather than just Halloween.</p><p class=\"footnote\">This page is just a temporary placeholder while the redirect is being rolled out.</p>"}],"hideTranslations":true}

=== frankkulak/mods-web-data/build/mods/pack-tests.json
{"name":"Pack Tests","tagline":"Utility for modders","description":"If you ever need to test whether your users have a particular pack installed or not, this script will allow you to do so directly in tuning - no scripting abilities required!","version":"1.0.1","lastUpdated":"July 20, 2021","stage":"public","status":"untested","hideTranslations":true,"pages":[{"title":"For Users","html":"<h2>What does this mod do?</h2><p>It makes it easier for modders to check whether you have certain packs installed.</p><p class=\"footnote\">This is done to integrate mods with packs while keeping them compatible with the base game.</p><h2>Should I install this mod?</h2><p>Only if you're using another mod that requires it (its creator should tell you). You only have to install it once.</p><h2>What if I have every pack?</h2><p>You still need to install this mod if using another that requires it.</p><p class=\"footnote\">This script allows modders to write code that the game cannot understand on its own, so leaving this mod out can cause issues while loading their files.</p>"},{"title":"For Modders","html":"<p class=\"text-subtle\"><span class=\"danger font-bold\">STOP!</span> Before you consider using this mod, you should check out <a href=\"https://lot51.cc/core\" target=\"_blank\">Lot51's Core Library</a>. It supports many features, including pack tests.</p><h2>What can this mod do for me?</h2><p>This mod adds a tunable test set that can check whether certain packs are installed or not. You can then reference these test sets anywhere you normally would (e.g. in a loot, interaction, etc.). This is all done via tuning, so you do not have to write a script of your own.</p><h2>How often will this mod be updated?</h2><p>This mod is only updated when absolutely necessary (i.e. when it breaks after a patch), and these are just updates to the script. So, you should never have to update your tuning when this mod updates - your users just have to update this mod.</p><h2>How can I use this mod?</h2><div class=\"paragraphs\"><p>Download the modders' documentation to get started - it will show you how you can write and use your own pack test sets.</p><p><span class=\"font-bold\">Do not include my script in your own download, and do not re-upload it anywhere</span>*. Doing so will inevitably lead to users having the same code in their game multiple times, and it will cause issues for them if this mod is ever updated.</p><p class=\"footnote\">*If you'd like to implement your own pack test based on my code, you are 100% free to do so. Just do not copy the files exactly as-is, or we may have conflicts.</p></div>"},{"title":"Changelog","html":"<h2>1.0.1 (July 20, 2021)</h2><ul><li>Fix issue that resulted from the Cottage Living patch.</li></ul><h2>1.0 (January 4, 2021)</h2><ul><li>Add pack test set.</li></ul>"}],"documentation":[{"host":"Sim File Share","href":"http://www.simfileshare.net/download/2251516/"}],"downloads":[{"host":"Sim File Share","href":"http://www.simfileshare.net/download/2251515/"},{"host":"Google Drive","href":"https://drive.google.com/drive/folders/19Xw1Yt1FEvT2AzZmnq7dYwe6ImgDZKiv?usp=sharing"}]}

=== frankkulak/mods-web-data/data/mods/show-sim-info/index.json
{
  "$schema": "../../../schemas/mod.schema.json",
  "name": "Show Sim Info",
  "tagline": "View internal sim data",
  "description": "View all of the internal data for particular sims with an interaction. Originally by Itasan on MTS.",
  "version": "3.8.10",
  "lastUpdated": "September 6, 2025",
  "stage": "public",
  "status": "untested",
  "hideTranslations": true,
  "pages": [
    {
      "title": "Details",
      "html": "details.html"
    },
    {
      "title": "Changelog",
      "html": "changelog.html"
    }
  ],
  "downloadWarning": "If you have downloaded this mod from Mod The Sims, delete that version before installing this one. Note that using a cloud service (OneDrive, Google Drive, iCloud, etc.) to back up your Mods folder can cause files to stick around even after you think you've deleted them.",
  "downloads": [
    {
      "host": "Sim File Share",
      "href": "http://simfileshare.net/folder/167469/"
    },
    {
      "host": "Google Drive",
      "href": "https://drive.google.com/drive/folders/1LysKnKrwf_dkunwtNRuBnDa81p0WeGX-?usp=sharing"
    }
  ]
}

=== frankkulak/mods-web-data/data/mods/festive-milestones/index.json
{
  "$schema": "../../../schemas/mod.schema.json",
  "name": "Festive Milestones",
  "tagline": "Milestones for events and holidays",
  "description": "Your sims should remember their special days. This mod adds milestones for events, festivals, and holidays from various packs.",
  "version": "1.0 alpha 3",
  "lastUpdated": "June 12, 2023",
  "stage": "alpha",
  "earlyAccess": "alpha",
  "status": "working",
  "seoTags": [
    "festive",
    "festival",
    "event",
    "holiday",
    "developmental",
    "milestone",
    "memories"
  ],
  "requiredPacks": {
    "eps": [
      "Growing Together"
    ]
  },
  "recommendedPacks": {
    "eps": [
      "City Living",
      "Island Living",
      "Seasons",
      "Snowy Escape"
    ]
  },
  "pages": [
    {
      "title": "Details",
      "html": "details.html"
    },
    {
      "title": "Changelog",
      "html": "changelog.html"
    }
  ],
  "translations": [
    {
      "code": "ENG_US",
      "translators": [
        {
          "name": "Frankk"
        }
      ]
    }
  ],
  "downloads": [
    {
      "host": "Patreon",
      "href": "https://www.patreon.com/posts/84386385"
    }
  ],
  "downloadWarning": "Alpha releases are incomplete snapshots of mods while they are being developed. Currently, everything but City Living is complete. You must own Growing Together and one of the supported packs to use v1.0 alpha 3."
}

=== frankkulak/mods-web-data/data/mods/halloween-holiday/index.json
{
  "$schema": "../../../schemas/mod.schema.json",
  "name": "Halloween Holiday",
  "tagline": "Adds Halloween to the calendar",
  "description": "Tired of manually adding Halloween to the calendar? This mod will make it appear by default, just like the other holidays.",
  "version": "1.0 beta 2",
  "lastUpdated": "June 8, 2023",
  "stage": "beta",
  "earlyAccess": "beta",
  "publicRelease": "June 14, 2023",
  "status": "working",
  "seoTags": [
    "halloween",
    "holiday",
    "calendar",
    "seasons"
  ],
  "requiredPacks": {
    "eps": [
      "Seasons"
    ]
  },
  "pages": [
    {
      "title": "Details",
      "html": "details.html"
    },
    {
      "title": "Changelog",
      "html": "changelog.html"
    }
  ],
  "translations": [
    {
      "code": "ENG_US",
      "translators": [
        {
          "name": "Frankk"
        }
      ]
    }
  ],
  "downloads": [
    {
      "host": "Patreon",
      "href": "https://www.patreon.com/posts/84235940"
    }
  ],
  "downloadWarning": "To rename the holiday, edit the contents of HolidayNameOverride.txt. If you like the name \"Halloween\", you can delete this file."
}

=== frankkulak/mods-web-data/data/mods/bunpocalypse/index.json
{
  "$schema": "../../../schemas/mod.schema.json",
  "name": "Bunpocalypse",
  "tagline": "You want bunnies, you get bunnies",
  "description": "Go ahead, try to escape the bunnies. I dare you.",
  "version": "1.0",
  "lastUpdated": "April 1, 2023",
  "stage": "public",
  "status": "untested",
  "hasNoCustomStrings": true,
  "seoTags": [
    "bunny",
    "rabbit",
    "chaos",
    "funny",
    "weird"
  ],
  "pages": [
    {
      "title": "Details",
      "html": "details.html"
    },
    {
      "title": "Changelog",
      "html": "changelog.html"
    }
  ],
  "downloadWarning": "Please look at the date this mod was posted, and don't take it too seriously. Also, you probably shouldn't save your game while using this mod.",
  "downloads": [
    {
      "host": "Google Drive",
      "href": "https://drive.google.com/file/d/1VJnEqq4MYueiI3tBl930x_CW3OHDTKLR/view?usp=share_link"
    }
  ],
  "requiredPacks": {
    "eps": [
      "Cottage Living"
    ]
  },
  "hideTranslations": true
}

=== frankkulak/mods-web-data/build/mods/custom-holiday-fix.json
{"name":"Custom Holiday Fix","tagline":"Makes custom holidays behave","description":"Enable custom holidays in existing saves, and get rid of that pesky exception notification caused by uninstalling them.","version":"1.0","lastUpdated":"June 15, 2023","stage":"wip","status":"unreleased","hideTranslations":true,"pages":[{"title":"For Users","html":"<div class=\"paragraphs\"><h2>What does this mod do?</h2><ul><li>Makes it easy for other modders to add custom holidays</li><li>Allows custom holidays to appear in existing saves</li><li>Fixes an error that occurs after uninstalling custom holidays</li><p class=\"footnote\"><span class=\"font-bold danger\">Important:</span> For this to work, this mod must be kept in your game even after uninstalling custom holidays. It works by detecting when the custom holiday is no longer installed. You can remove this mod after uninstalling the holiday, launching your game, and saving.</p></ul></div><div class=\"paragraphs\"><h2>Should I install this mod?</h2><p>If you intend on using any custom holiday mods, even ones that do not list this mod as a requirment, then <span class=\"font-bold\">YES</span>.</p><p>This mod works across-the-board, not just on ones that use this mod's method of adding holidays to the calendar - this means that those other custom holidays will appear in existing saves, and be removed properly when uninstalled.</p></div>"},{"title":"For Modders","html":"<h2>What can this mod do for me?</h2><p>This mod makes it easy for you to add custom holidays to the calendar in a safer way, using a snippet - no scripting required. It also ensures that your holiday will appear in existing saves, and that it does not cause exceptions when uninstalled.</p><h2>How can I use this mod?</h2><p>Download the modders' documentation to get started - it will show you how you can write and use your holiday injector snippet.</p><hr><h2 class=\"danger\">Important notice</h2><p>Do not include my script in your own download, and do not re-upload it anywhere. Doing so will inevitably lead to users having the same code in their game multiple times, and it <span class=\"font-bold\">WILL</span> cause issues. Remember, this is not just an injector, but also a fix.</p>"},{"title":"Changelog","html":"<h2>1.0 (June 15, 2023)</h2><ul><li>Add snippet for injecting custom holidays.</li><li>Retroactively add custom holidays to existing saves.</li><li>Remove uninstalled custom holidays from saves they're included in.</li></ul>"}],"requiredPacks":{"eps":["Seasons"]}}

=== frankkulak/mods-web-data/build/mods/utter-chaos.json
{"name":"Utter Chaos","tagline":"Your sims will hate this","description":"Saying \"hello\" to your neighbor? You just might burst into flames, turn into an alien, or both. This mod adds a chance for random outcomes to every action in the game.","version":"1.0 beta 1","lastUpdated":"January 16, 2022","stage":"public","status":"untested","hasNoCustomStrings":true,"seoTags":["chaos","chaotic","funny","weird","fire","skeleton","chicken"],"pages":[{"title":"Details","html":"<h2>What does this mod do?</h2><ul><li>Whenever a sim does anything, there is a chance for the outcome of their action to be randomized.</li><p class=\"footnote\">1 out of every 400 random outcomes will involve fire, but the other 399 can be anything from a notification to an alien abduction.</p><li>Random outcomes also count as actions, and can trigger even more randomness.</li><p class=\"footnote\">When it rains, it pours. Have fun.</p></ul><br><div class=\"images-md\"><img data-src=\"mermaid\"> <img data-src=\"buffs\"> <img data-src=\"bella\"> <img data-src=\"cake\"></div><h2>Warnings & known issues</h2><ul><li>For some reason, the randomizer <em>loves</em> picking outcomes related to skeletons and chickens. This is not a joke. You'll see what I mean.</li><p class=\"footnote\"><strong>Tip</strong>: To reduce notification spam from the mystical baby chicken, <a href=\"https://jamesturner.yt/disablepacks\" target=\"_blank\">disable the Cottage Living EP</a>.</p><li>Other gameplay mods may perform actions in the background, and cause an unbearable amount of randomized outcomes.</li><p class=\"footnote\"><strong>Tip</strong>: Remove other gameplay mods before playing with Utter Chaos.</p><li>You <em>will</em> see \"exception\" notifications if you use MC Command Center or Better Exceptions, due to the high degree of randomness this mod produces.</li><p class=\"footnote\"><strong>Tip</strong>: This is unavoidable, and may be annoying. Consider removing these mods while using Utter Chaos.</p></ul><br><p class=\"danger\"><strong>WARNING!</strong> Do not use this mod in saves that you care about. Seriously. Your sims can and will have their lives turned upside down in an instant, and can die without warning. Your builds may also be at risk due to the number of fires this mod starts. You've been warned, use this mod at your own risk.</p>"},{"title":"Changelog","html":"<h2>1.0 beta 1 (January 16, 2022)</h2><ul><li>Incite chaos.</li></ul>"}],"downloadWarning":"This mod is just for dumb fun. You should not be using it in saves that you care about, because anything can happen at any moment (including death). Do not report issues to mod creators while you have this mod installed.","downloads":[{"host":"Sim File Share","href":"http://www.simfileshare.net/download/2929952/"},{"host":"Google Drive","href":"https://drive.google.com/file/d/1ufzQziu243gPupzp4LAamW22qSFQXVf5/view?usp=sharing"}],"videos":[{"creator":"CallMeKevin","name":"A sims mod that makes every choice random","href":"https://youtu.be/-8nblI9gGJ0","platform":"YouTube"},{"creator":"CallMeKevin","name":"I trapped an entire Sims Neighborhood in one house","href":"https://youtu.be/MOKe-XeSxII","platform":"YouTube"}]}
